import os
SECRET_KEY = os.urandom(32)

# Grabs the folder where the script runs.
basedir = os.path.abspath(os.path.dirname(__file__))

auth0_config = {
    "AUTH0_DOMAIN": "dev-lulu.us.auth0.com",
    "ALGORITHMS": ["RS256"],
    "API_AUDIENCE": "capstoneAPI"
}


pagination = {
    "example": 10  # Limits returned rows of API
}

bearer_tokens = {
    "casting_assistant": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImR5cEN1b1VCMGFnd3dLU2wyNzBuTyJ9.eyJpc3MiOiJodHRwczovL2Rldi1sdWx1LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2MDExNThjNTY4YmYxODAwNjllZDcwOTciLCJhdWQiOiJjYXBzdG9uZUFQSSIsImlhdCI6MTYxMTc4NTE5MiwiZXhwIjoxNjExODcxNTkyLCJhenAiOiJybWI2WHhTd21HSkRaR3pkMHdpUFhMTTRQNzlaeWhsbyIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZ2V0OmFjdG9ycyIsImdldDptb3ZpZXMiXX0.fu8OOQ2aOAws3pNMi_FLrWwxswJZvraxx_dLMpUjcyVVw-qLKenWRpb86K6kwixDPKoutpTjXkg24FL-Mt-0UJjMFhguqUuhgOxTWZiOS0zf6NKc8mmLCT6qYOCeEJbm2_6eGhrKy0JUJtj5WRomehlt46EURKsURt0ANbhe7aCKTs4Smzt1TAxZaffoikwUpa2kNyGu4hfySkkeWZ8iKepRpYR4cbZcVQs29a3aLd-5fwWFPUyJRsn57Wu8R3k9fn7_RYjCWcwpt7PLNXphxcuHYZBNPuRD4gDIq9JgzjHer8b_zzRI-UhJtYRTJ2QKowy1AA4uezSqlsZlK1mEwA",
    "executive_producer": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImR5cEN1b1VCMGFnd3dLU2wyNzBuTyJ9.eyJpc3MiOiJodHRwczovL2Rldi1sdWx1LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZmFhZDI0OWI1YmRhMjAwNjk2NDc4ZDUiLCJhdWQiOiJjYXBzdG9uZUFQSSIsImlhdCI6MTYxMTc4NTM5MSwiZXhwIjoxNjExODcxNzkxLCJhenAiOiJybWI2WHhTd21HSkRaR3pkMHdpUFhMTTRQNzlaeWhsbyIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9ycyIsImRlbGV0ZTptb3ZpZSIsImVkaXQ6YWN0b3JzIiwiZWRpdDptb3ZpZXMiLCJnZXQ6YWN0b3JzIiwiZ2V0Om1vdmllcyIsInBvc3Q6YWN0b3JzIiwicG9zdDptb3ZpZXMiXX0.mq8BtDZJVrtiJe1ZwFEes0vHkCPvJk8IpW7KKZctmeN9WRRoE9TQqEEr1y9BFOTkQGVGywbU46ASMBHv2gQ1vfE_M0w3r4n0sDFjv-el6qiBIvZseWqgMmwNR5lbabSTtr25OWWODQslslUDRTTsvd72pPoAsU0_4KpH1cEtIVFLiA5I4_rLuaxjjFixFvkAFuGdGmn4AjGxC1FBanjTjdItuFV3bbahKb2CJp_L2lAnO8DQlVrTJJkthOWXaHY2aaHJ3HLC9JIhRcPUgT3jxYsTvriAVDQ83XUSUpLKZ1LAm87sPcfxha2dp2hAG2pGm20RsM9vP43LniF-Ilac7g",
    "casting_director": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImR5cEN1b1VCMGFnd3dLU2wyNzBuTyJ9.eyJpc3MiOiJodHRwczovL2Rldi1sdWx1LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZmI1MDVlMzE4NjZiNDAwNjg2N2YyZjIiLCJhdWQiOiJjYXBzdG9uZUFQSSIsImlhdCI6MTYxMTc4NTI4OSwiZXhwIjoxNjExODcxNjg5LCJhenAiOiJybWI2WHhTd21HSkRaR3pkMHdpUFhMTTRQNzlaeWhsbyIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9ycyIsImVkaXQ6YWN0b3JzIiwiZWRpdDptb3ZpZXMiLCJnZXQ6YWN0b3JzIiwiZ2V0Om1vdmllcyIsInBvc3Q6YWN0b3JzIl19.YqdLTYTk7lHkeUcYpgScaylosAVcW7W2EV6RYGLQVeyZgAq7iCC1ZrhK0Lpz-XkEpR-pdbYeeFTV99SAa0eJ4YSP6_wPK6_HtMWVG9FTyIoeJTDD3K0rROD1Nfw4yvSliZxqtKmQsU7csa_C-CCCNjqpPByntrWEmDxc2Q0Sk08EjaUIuPK77CjzU24nrFT7LUZEGvVXPbS8BDalWgibcbw_XqKcNJILYhOzhYU3JmOWJdzqEDqxfUqsoadLtT-vXaUNjS5eiFpr1y3OA0jxDafZCSf4PEjTBP5w8nreoD7KWiOka3wAtf4g_lycHk-8OAznNHNU2X_nbKHpiwrQTQ"
}
